// apps/web/src/app/(app)/main/explore/_data/worldRegions.ts
//
// AUTO-GENERATED alongside the API's worldPlaces.ts, from UNESCO's own regional
// grouping. Regenerate with scratchpad/world/build-world.mjs.
//
// The World lane has 153 places, and the deck endpoint returns every one of them
// unranked — so the landing needs somewhere to put them. UNESCO already groups
// the world into regions, which is a truer browse than an alphabetical wall:
// pick a part of the world, then a place in it.

export const WORLD_REGION_BY_SLUG: Record<string, string> = {
  "afghanistan": "Asia and the Pacific",
  "albania": "Europe and North America",
  "algeria": "Arab States",
  "andorra": "Europe and North America",
  "argentina": "Latin America and the Caribbean",
  "armenia": "Europe and North America",
  "australia": "Asia and the Pacific",
  "austria": "Europe and North America",
  "azerbaijan": "Asia and the Pacific,Europe and North America",
  "bahrain": "Arab States",
  "bangladesh": "Asia and the Pacific",
  "belarus": "Europe and North America",
  "belgium": "Europe and North America",
  "belize": "Latin America and the Caribbean",
  "benin": "Africa",
  "bolivia-plurinational-state-of": "Latin America and the Caribbean",
  "bosnia-and-herzegovina": "Europe and North America",
  "botswana": "Africa",
  "brazil": "Latin America and the Caribbean",
  "bulgaria": "Europe and North America",
  "burkina-faso": "Africa",
  "c-xf4-te-d-apos-ivoire": "Africa",
  "cambodia": "Asia and the Pacific",
  "cameroon": "Africa",
  "canada": "Europe and North America",
  "central-african-republic": "Africa",
  "chad": "Africa",
  "chile": "Latin America and the Caribbean",
  "china": "Asia and the Pacific",
  "colombia": "Latin America and the Caribbean",
  "congo": "Africa",
  "costa-rica": "Latin America and the Caribbean",
  "c-te-d-ivoire": "",
  "croatia": "Europe and North America",
  "cuba": "Latin America and the Caribbean",
  "cyprus": "Europe and North America",
  "czechia": "Europe and North America",
  "democratic-people-s-republic-of-korea": "",
  "democratic-people-apos-s-republic-of-korea": "Asia and the Pacific",
  "democratic-republic-of-the-congo": "Africa",
  "denmark": "Europe and North America",
  "djibouti": "",
  "dominican-republic": "Latin America and the Caribbean",
  "ecuador": "Latin America and the Caribbean",
  "egypt": "Arab States",
  "estonia": "Europe and North America",
  "ethiopia": "Africa",
  "finland": "Europe and North America",
  "france": "Europe and North America",
  "gabon": "Africa",
  "gambia": "Africa",
  "georgia": "Europe and North America",
  "germany": "Europe and North America",
  "ghana": "Africa",
  "greece": "Europe and North America",
  "guatemala": "Latin America and the Caribbean",
  "haiti": "Latin America and the Caribbean",
  "honduras": "Latin America and the Caribbean",
  "hungary": "Europe and North America",
  "iceland": "Europe and North America",
  "india": "Asia and the Pacific",
  "indonesia": "Asia and the Pacific",
  "iran-islamic-republic-of": "Asia and the Pacific,Europe and North America",
  "iraq": "Arab States",
  "ireland": "Europe and North America",
  "israel": "Europe and North America",
  "italy": "Europe and North America",
  "jamaica": "Latin America and the Caribbean",
  "japan": "Asia and the Pacific",
  "jordan": "Arab States",
  "kazakhstan": "Asia and the Pacific",
  "kenya": "Africa",
  "kuwait": "",
  "kyrgyzstan": "Asia and the Pacific",
  "lao-people-s-democratic-republic": "",
  "lao-people-apos-s-democratic-republic": "Asia and the Pacific",
  "latvia": "Europe and North America",
  "lebanon": "Arab States",
  "libya": "Arab States",
  "lithuania": "Europe and North America",
  "luxembourg": "Europe and North America",
  "madagascar": "Africa",
  "malawi": "Africa",
  "malaysia": "Asia and the Pacific",
  "mali": "Africa",
  "malta": "Europe and North America",
  "mauritania": "Arab States",
  "mauritius": "Africa",
  "mexico": "Latin America and the Caribbean",
  "mongolia": "Asia and the Pacific,Europe and North America",
  "montenegro": "Europe and North America",
  "morocco": "Arab States",
  "mozambique": "Africa",
  "myanmar": "Asia and the Pacific",
  "namibia": "Africa",
  "nepal": "Asia and the Pacific",
  "netherlands-kingdom-of-the": "Europe and North America",
  "new-zealand": "Asia and the Pacific",
  "nicaragua": "Latin America and the Caribbean",
  "niger": "Africa",
  "nigeria": "Africa",
  "north-macedonia": "Europe and North America",
  "norway": "Europe and North America",
  "oman": "Arab States",
  "pakistan": "Asia and the Pacific",
  "panama": "Latin America and the Caribbean",
  "paraguay": "Latin America and the Caribbean",
  "peru": "Latin America and the Caribbean",
  "philippines": "Asia and the Pacific",
  "poland": "Europe and North America",
  "portugal": "Europe and North America",
  "qatar": "Arab States",
  "republic-of-korea": "Asia and the Pacific",
  "republic-of-moldova": "",
  "romania": "Europe and North America",
  "russian-federation": "Europe and North America",
  "rwanda": "Africa",
  "saudi-arabia": "Arab States",
  "senegal": "Africa",
  "serbia": "Europe and North America",
  "seychelles": "Africa",
  "singapore": "Asia and the Pacific",
  "slovakia": "Europe and North America",
  "slovenia": "Europe and North America",
  "south-africa": "Africa",
  "spain": "Europe and North America",
  "sri-lanka": "Asia and the Pacific",
  "state-of-palestine": "Arab States",
  "sudan": "Arab States",
  "suriname": "Latin America and the Caribbean",
  "sweden": "Europe and North America",
  "switzerland": "Europe and North America",
  "syrian-arab-republic": "Arab States",
  "t-xfc-rkiye": "Europe and North America",
  "tajikistan": "Asia and the Pacific",
  "thailand": "Asia and the Pacific",
  "togo": "Africa",
  "tunisia": "Arab States",
  "t-rkiye": "",
  "turkmenistan": "Asia and the Pacific",
  "uganda": "Africa",
  "ukraine": "Europe and North America",
  "united-arab-emirates": "Arab States",
  "united-kingdom-of-great-britain-and-northern-ireland": "Europe and North America",
  "united-republic-of-tanzania": "Africa",
  "united-states-of-america": "Europe and North America",
  "uruguay": "Latin America and the Caribbean",
  "uzbekistan": "Asia and the Pacific",
  "venezuela-bolivarian-republic-of": "Latin America and the Caribbean",
  "viet-nam": "Asia and the Pacific",
  "yemen": "Arab States",
  "zambia": "Africa",
  "zimbabwe": "Africa"
};

// The order they read in, broadest and most familiar first.
export const WORLD_REGION_ORDER: string[] = [
  "Africa",
  "Arab States",
  "Asia and the Pacific",
  "Asia and the Pacific,Europe and North America",
  "Europe and North America",
  "Latin America and the Caribbean"
];
