name: Deploy EverleapUI to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install + Build
        run: |
          cd apps/web
          npm install
          npm run build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "EverleapUI"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_907494C4D91D422CB5AA91EEA851CB8 }}
          package: apps/web